.PHONY: default run install build build-release build-tiny
default: run

run:
	nimble run

build:
	nimble build

build-release:
	nimble build -d:release

build-tiny:
	nimble build -d:release --opt:size

install:
	nimble install
