[package]
name = "aoc2022"
version = "0.1.0"

[[bin]]
name = "day1"
path = "src/day1.rs"

[[bin]]
name = "day2"
path = "src/day2.rs"

[[bin]]
name = "day2-alt1"
path = "src/day2-alt1.rs"

[[bin]]
name = "day3"
path = "src/day3.rs"

[dependencies]
