[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"
include = ["common.rs"]

[[bin]]
name = "day16"
path = "day16.rs"

[[bin]]
name = "day17"
path = "day17.rs"

[[bin]]
name = "day18"
path = "day18.rs"

[dependencies]
